name: Backup Supabase Bunny's INK

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Crear carpeta de respaldo
        run: mkdir -p supabase-backup

      - name: Respaldar roles
        run: >
          supabase db dump
          --db-url "postgresql://postgres.zggngzzaxnujwbrhnabb:${SUPABASE_DB_PASSWORD}@aws-0-us-west-2.pooler.supabase.com:5432/postgres"
          -f supabase-backup/roles.sql
          --role-only
        env:
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}

      - name: Respaldar estructura
        run: >
          supabase db dump
          --db-url "postgresql://postgres.zggngzzaxnujwbrhnabb:${SUPABASE_DB_PASSWORD}@aws-0-us-west-2.pooler.supabase.com:5432/postgres"
          -f supabase-backup/schema.sql
        env:
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}

      - name: Respaldar datos
        run: >
          supabase db dump
          --db-url "postgresql://postgres.zggngzzaxnujwbrhnabb:${SUPABASE_DB_PASSWORD}@aws-0-us-west-2.pooler.supabase.com:5432/postgres"
          -f supabase-backup/data.sql
          --data-only
          --use-copy
        env:
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}

      - name: Guardar respaldo como archivo privado
        uses: actions/upload-artifact@v4
        with:
          name: Bunnys-INK-Supabase-Backup-v1.2
          path: supabase-backup/
          retention-days: 7
